// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLxkDKZNZjN5yaY-5Bw9_JBtOV4oo4Jo',
    appId: '1:231875555899:web:7c536068c8271af255221e',
    messagingSenderId: '231875555899',
    projectId: 'flutter-15d5a',
    authDomain: 'flutter-15d5a.firebaseapp.com',
    storageBucket: 'flutter-15d5a.firebasestorage.app',
    measurementId: 'G-D8PRQH76GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA57whZTBJc7SGgHhhVQMcicUaWHn-bqZA',
    appId: '1:231875555899:android:35e669d212a8e78255221e',
    messagingSenderId: '231875555899',
    projectId: 'flutter-15d5a',
    storageBucket: 'flutter-15d5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8s6H3QDGMFgDz517IMwbqsjEV-9m0k1s',
    appId: '1:231875555899:ios:e11c8fbaa44126d455221e',
    messagingSenderId: '231875555899',
    projectId: 'flutter-15d5a',
    storageBucket: 'flutter-15d5a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8s6H3QDGMFgDz517IMwbqsjEV-9m0k1s',
    appId: '1:231875555899:ios:e11c8fbaa44126d455221e',
    messagingSenderId: '231875555899',
    projectId: 'flutter-15d5a',
    storageBucket: 'flutter-15d5a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHLxkDKZNZjN5yaY-5Bw9_JBtOV4oo4Jo',
    appId: '1:231875555899:web:d9cf90126c7d876255221e',
    messagingSenderId: '231875555899',
    projectId: 'flutter-15d5a',
    authDomain: 'flutter-15d5a.firebaseapp.com',
    storageBucket: 'flutter-15d5a.firebasestorage.app',
    measurementId: 'G-2MEGPNLQZ6',
  );
}
